# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GTEmptyKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GTEmptyKit

  target 'GTEmptyKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GTEmptyKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'DZNEmptyDataSet'
  pod 'MJRefresh'


end
